#!/usr/bin/env python
"""
Point cloud processor / filter chain.
"""
from __future__ import absolute_import, division, print_function
from cloud_proc import configure_filters, FilterChain
import rospy
from ros_numpy import msgify, numpify
from sensor_msgs.msg import PointCloud2
from timeit import default_timer as timer


class CloudProcNode(object):

    def __init__(self):
        self.chain = FilterChain(configure_filters(rospy.get_param('~filters', [])))
        self.cloud_pub = rospy.Publisher('out', PointCloud2, queue_size=2)
        self.cloud_sub = rospy.Subscriber('in', PointCloud2, self.cloud_cb, queue_size=2)
        self.overwrite_in_frame = rospy.get_param('~overwrite_in_frame', None)

    def cloud_cb(self, msg):
        t0 = timer()
        # Create a copy which can be modified in-place.
        cloud = numpify(msg).copy()
        header = msg.header
        if self.overwrite_in_frame is not None:
            header.frame_id = self.overwrite_in_frame
        cloud, header = self.chain.filter(cloud, header)
        if cloud is not None:
            msg = msgify(PointCloud2, cloud)
            msg.header = header
            self.cloud_pub.publish(msg)
        rospy.loginfo('Cloud processed (%.3f s).' % (timer() - t0))


if __name__ == '__main__':
    rospy.init_node('cloud_proc')
    node = CloudProcNode()
    rospy.spin()
